### PR TITLE
Moves route change into setState callback

### PR DESCRIPTION
**Pull request by jessicamarcus**
Resolves https://rollbar.com/CityofBoston/registry-certs/items/154/

When an order has been submitted, we need to ensure that state updates have been completed before the route changes.

### CODE REVIEW

**Comment by fionawhim** [comment]
What does the `CheckoutPage` end up looking like in this case? It seems that `render` might flash a blank order of some kind.

**Comment by jessicamarcus** [comment]
I didn’t notice anything jarring, but I could push it to staging and see what it looks like to Bruti (and whomever)?

**Comment by fionawhim** [comment]
One good test is to remove the `Router.push` call and see what happens to the UI.

Then you can decide if you want to keep that, or remove the `setState` entirely.

**Comment by jessicamarcus** [comment]
Ah, good call. When I tried removing the `setState`, the UI would hang. 🤔

**Comment by jessicamarcus** [comment]
I’ve done some more testing and the transition from “order submitting” to the confirmation page is visually instantaneous. I tried a throttled connection, same result.

**Review by fionawhim — APPROVED** [review]

**Pull request merged**
