### PR TITLE
DIG-3256: Marriage Intention UI/UX Updates (EPIC)

### PR DESCRIPTION
**Pull request by phillipbentonkelly**
### (EPIC) DIG-3256: Marriage Intention UI/UX update to meet COB Gender Guidelines

- [x] [DIG-3306: Review Marriage Intention Form Updates to Organize work](https://bostondoit.atlassian.net/browse/DIG-3306)
- [x] [DIG-3665: UI/UX Update Registry Marriage Intention Form - Navigation ](https://bostondoit.atlassian.net/browse/DIG-3665)
- [x] [DIG-3685: Fix Application state to use one person template](https://bostondoit.atlassian.net/browse/DIG-3685)
- [x] [DIG-3449: UI/UX Update Registry Marriage Intention - Getting Started](https://bostondoit.atlassian.net/browse/DIG-3449)
- [x] [DIG-3953: Add Missing Storybook file For Marriage Intention Form Pages](https://bostondoit.atlassian.net/browse/DIG-3953)
- [x] [DIG-3450: UI/UX Update Registry Marriage Intention - Review Form](https://bostondoit.atlassian.net/browse/DIG-3953)
- [x] [DIG-3649: UI/UX Update Registry Marriage Intention - Contact Information ](https://bostondoit.atlassian.net/browse/DIG-3649)
- [x] [DIG-3451 UI/UX Update Registry Marriage Intention - Submit Form](https://bostondoit.atlassian.net/browse/DIG-3451)
- [x] [DIG-3452: UI/UX Update Registry Marriage Intention - Person 1 - Personal Information](https://bostondoit.atlassian.net/browse/DIG-3452)
- [x] [DIG-3558: UI/UX Update Registry Marriage Intention - Date & Place of Birth](https://bostondoit.atlassian.net/browse/DIG-3558)
- [x] [DIG-3557: UI/UX Update Registry Marriage Intention - Hover Text](https://bostondoit.atlassian.net/browse/DIG-3557)
- [x] [DIG-3568: UI/UX Update Registry Marriage Intention - Person 1/2 Residence](https://bostondoit.atlassian.net/browse/DIG-3568)
- [x] [DIG-3569: UI/UX Update Registry Marriage Intention - Person 1/2 Marriage](https://bostondoit.atlassian.net/browse/DIG-3569)
- [x] [DIG-3571: UI/UX Update Registry Marriage Intention - Person 1/2 Parents](https://bostondoit.atlassian.net/browse/DIG-3571)
- [x] [DIG-4058: Text Box treatments for data entry states and required fields](https://bostondoit.atlassian.net/browse/DIG-4058)
- [x] [DIG-4059: Navigation Bar and Next Button behavior is aligned](https://bostondoit.atlassian.net/browse/DIG-4059)
- [x] [DIG-4375: UX updates for Marriage Intention form ](https://bostondoit.atlassian.net/browse/DIG-4375)
- [x] [DIG-4409: Final Marriage Intention fixes before Registry review](https://bostondoit.atlassian.net/browse/DIG-4409)
- [x] [DIG-4557: Test solution to not print surname of Parent 1/2](https://bostondoit.atlassian.net/browse/DIG-4557)
- [x] [DIG-4558: Marriage Intention Language Updates](https://bostondoit.atlassian.net/browse/DIG-4558)
- [x] [DIG-4453: (Bug) Tooltip goes beyond the design](https://bostondoit.atlassian.net/browse/DIG-4453)
- [x] Re-point components CSS back to PROD (patterns.boston.gov) CSS

### CODE REVIEW

**Comment by phillipbentonkelly** [comment]
@subaha-cob @davidrkupton Tagged you for review to get back in the habit, not expecting you to actually review this `Monster` 😄

**Review by davidrkupton — DISMISSED** [review]
LGTM!

**Review by subaha-cob — DISMISSED** [review]
You are right, I tried, gave up one third way through. lol
LGTM! 😂

**Review by subaha-cob — DISMISSED** [review]
LGTM!

**Review by subaha-cob — APPROVED** [review]
LGTM!

**Pull request merged**
