### PR TITLE
Upgrades to React and Next

### PR DESCRIPTION
**Pull request by fionawhim**
Also tweaks some other imports and modifies yarn.lock to try and reduce
the number of overlapping version ranges, especially for Babel imports.

### CODE REVIEW

**Comment by fionawhim** [comment]
I'm pushing all the apps to staging and checking them out.

**Review by jessicamarcus — APPROVED** [review]
💯

**Comment by jessicamarcus** [comment]
Wait - what’s going on in Percy for 311 & registry-certs?

**Review by jessicamarcus — CHANGES_REQUESTED** [review]
311 and registry-certs are showing as blank pages in Percy now... Sorry, should have waited for it to finish up :/

**Comment by fionawhim** [comment]
Investigating…

**Review by jessicamarcus — APPROVED** [review]
💯

**Pull request merged**
